---
driver:
  name: vagrant
  vm_hostname: kitchen-nicwaller-hubot

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.14.89
  data_bags_path: test/integration/data_bags
  environments_path: test/integration/environments
  client_rb:
    environment: DEV

platforms:
  - name: bento/ubuntu-14.04
  - name: bento/ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[nicwaller_hubot::default]