name               'nicwaller_hubot'
maintainer         'Nic Waller'
maintainer_email   'code@nicwaller.com'
license            'Apache License 2.0'
description        'Installs/Configures hubot'
long_description   'Installs/Configures hubot'
issues_url         'https://github.com/nicwaller/cookbook-nicwaller_hubot/issues'
source_url         'https://github.com/nicwaller/cookbook-nicwaller_hubot'
version            '0.1.0'

depends 'nodejs'